import { TranslationEntry } from './index';

/** Cele 4 pagini de personal din AdminShell (Rețineri, Blocklist,
 * Documente, Vedere client) — un singur dicționar comun, un prefix pe
 * sub-pagină. Textul generat de Guardian AI (explicația reținerii) și
 * datele reale (nume client, IBAN, titluri de documente) NU apar aici —
 * rămân netraduse intenționat (fază separată de i18n pe backend). */
export const STAFF_I18N: Record<string, TranslationEntry> = {
  // --- staff-holds -----------------------------------------------------
  'staffHolds.title': { ro: 'Rețineri de fraudă', en: 'Fraud holds' },
  'staffHolds.subtitle': {
    ro: 'Transferuri suspecte, oprite pentru revizuire manuală — sună clientul înainte de a decide.',
    en: 'Suspicious transfers, stopped for manual review — call the customer before deciding.',
  },
  'staffHolds.refresh': { ro: 'Actualizează', en: 'Refresh' },
  'staffHolds.noPhoneOnFile': { ro: 'Fără telefon în evidență', en: 'No phone on file' },
  'staffHolds.score': { ro: 'Scor', en: 'Score' },
  'staffHolds.aiAnalysis': { ro: 'Analiză AI', en: 'AI analysis' },
  'staffHolds.viewCustomerAccount': { ro: 'Vezi contul clientului', en: 'View customer account' },
  'staffHolds.reject': { ro: 'Respinge', en: 'Reject' },
  'staffHolds.approve': { ro: 'Aprobă', en: 'Approve' },
  'staffHolds.expiresAt': { ro: 'expiră', en: 'expires' },
  'staffHolds.loadError': { ro: 'Nu am putut încărca reținerile.', en: 'We could not load the holds.' },
  'staffHolds.loadErrorTitle': { ro: 'Nu am putut încărca reținerile', en: 'We could not load the holds' },
  'staffHolds.emptyTitle': { ro: 'Nicio reținere activă', en: 'No active holds' },
  'staffHolds.emptyDescription': {
    ro: 'Toate transferurile semnalate au fost deja rezolvate.',
    en: 'All flagged transfers have already been resolved.',
  },
  'staffHolds.ruleDescriptionFallback': {
    ro: 'Regulă de fraudă fără descriere înregistrată.',
    en: 'Fraud rule with no recorded description.',
  },
  'staffHolds.approveTitle': { ro: 'Aprobi transferul?', en: 'Approve the transfer?' },
  'staffHolds.rejectTitle': { ro: 'Respingi transferul?', en: 'Reject the transfer?' },
  'staffHolds.approveMessage': {
    ro: 'Fondurile vor fi eliberate imediat către beneficiar ({recipient}). Ai confirmat identitatea/intenția clientului la telefon?',
    en: 'Funds will be released immediately to the recipient ({recipient}). Have you confirmed the customer’s identity/intent by phone?',
  },
  'staffHolds.rejectMessage': {
    ro: 'Fondurile vor reveni imediat în contul clientului. Beneficiarul ({recipient}) NU va primi banii.',
    en: 'Funds will be returned immediately to the customer’s account. The recipient ({recipient}) will NOT receive the money.',
  },
  'staffHolds.approveToast': {
    ro: 'Transfer aprobat — fondurile au ajuns la beneficiar.',
    en: 'Transfer approved — funds have reached the recipient.',
  },
  'staffHolds.rejectToast': {
    ro: 'Transfer respins — fondurile au revenit la client.',
    en: 'Transfer rejected — funds have been returned to the customer.',
  },
  'staffHolds.resolveError': { ro: 'Nu am putut rezolva reținerea.', en: 'We could not resolve the hold.' },
  'staffHolds.guardianAnalysisTitle': { ro: 'Analiză Financial Guardian', en: 'Financial Guardian analysis' },
  'staffHolds.explanationPending': {
    ro: 'Analiza se generează încă — reîmprospătează pagina peste câteva secunde.',
    en: 'The analysis is still being generated — refresh the page in a few seconds.',
  },
  'staffHolds.guardianDisclaimer': {
    ro: 'Generat automat de Financial Guardian, pe baza regulilor determinist declanșate mai sus — informativ, nu înlocuiește verificarea telefonică a clientului.',
    en: 'Automatically generated by Financial Guardian, based on the deterministically triggered rules above — informational only, does not replace a phone verification with the customer.',
  },

  // Explicații pentru codurile de regulă (tooltip la hover pe rândul de
  // reținere) — vezi backend app/fraud/catalogue.py, cele 18 reguli fixe.
  'staffHolds.rule.AMT-01': {
    ro: 'Sumă de peste 2x cât transferă de obicei acest client (comparat cu ultimele 90 de zile).',
    en: 'Amount over 2x what this customer usually transfers (compared to the last 90 days).',
  },
  'staffHolds.rule.AMT-02': {
    ro: 'Sumă de peste 4x mediana categoriei respective pentru acest client (ultimele 90 de zile).',
    en: 'Amount over 4x the median for that category for this customer (last 90 days).',
  },
  'staffHolds.rule.AMT-03': {
    ro: 'Sumă de peste 70% din soldul disponibil al clientului.',
    en: 'Amount over 70% of the customer’s available balance.',
  },
  'staffHolds.rule.AMT-04': {
    ro: 'Sumă de peste 98% din soldul disponibil — practic golește contul.',
    en: 'Amount over 98% of the available balance — effectively empties the account.',
  },
  'staffHolds.rule.AMT-05': {
    ro: 'Primul transfer mare (5x media) al unui client cu istoric scurt (sub 20 de tranzacții).',
    en: 'First large transfer (5x average) from a customer with a short history (under 20 transactions).',
  },
  'staffHolds.rule.VEL-01': {
    ro: 'Peste 5 tranzacții în ultimele 10 minute.',
    en: 'Over 5 transactions in the last 10 minutes.',
  },
  'staffHolds.rule.VEL-02': {
    ro: 'Suma cumulată în ultima oră depășește de 3x media zilnică a clientului.',
    en: 'The amount accumulated in the last hour exceeds 3x the customer’s daily average.',
  },
  'staffHolds.rule.VEL-05': {
    ro: 'Sume tot mai mari trimise către ACELAȘI beneficiar în 30 de minute (tipar de "testare" înainte de golire de cont).',
    en: 'Increasingly larger amounts sent to the SAME recipient within 30 minutes ("testing" pattern before draining the account).',
  },
  'staffHolds.rule.BEN-01': {
    ro: 'Prima plată vreodată către acest beneficiar.',
    en: 'The first payment ever to this recipient.',
  },
  'staffHolds.rule.BEN-03': {
    ro: 'Țara IBAN-ului destinație nu apare în istoricul clientului.',
    en: 'The destination IBAN’s country does not appear in the customer’s history.',
  },
  'staffHolds.rule.BEN-05': {
    ro: 'Beneficiarul a primit bani de la 5+ expeditori diferiți în ultimele 24h (posibil cont-mulă).',
    en: 'The recipient received money from 5+ different senders in the last 24h (possible mule account).',
  },
  'staffHolds.rule.TIME-01': {
    ro: 'Ora tranzacției e în afara intervalului obișnuit de activitate al clientului.',
    en: 'The transaction time is outside the customer’s usual activity window.',
  },
  'staffHolds.rule.TIME-02': {
    ro: 'Prima activitate a clientului după peste 90 de zile de inactivitate.',
    en: 'The customer’s first activity after more than 90 days of inactivity.',
  },
  'staffHolds.rule.DEV-03': {
    ro: 'Un passkey nou a fost înregistrat pe cont în ultimele 60 de minute.',
    en: 'A new passkey was registered on the account in the last 60 minutes.',
  },
  'staffHolds.rule.BEH-01': {
    ro: 'Categorie de cheltuială pe care acest client n-a mai folosit-o niciodată.',
    en: 'A spending category this customer has never used before.',
  },
  'staffHolds.rule.BEH-02': {
    ro: 'Categorie folosită în mai puțin de 5% din istoricul clientului.',
    en: 'A category used in less than 5% of the customer’s history.',
  },
  'staffHolds.rule.BEH-03': {
    ro: 'Bani primiți urmați de o retragere aproape egală în maxim 2 ore (posibil pass-through).',
    en: 'Money received followed by a near-equal withdrawal within 2 hours (possible pass-through).',
  },
  'staffHolds.rule.STR-02': {
    ro: 'Aceeași sumă exactă trimisă către 3+ beneficiari diferiți în 60 de minute (posibilă structurare).',
    en: 'The exact same amount sent to 3+ different recipients within 60 minutes (possible structuring).',
  },

  // --- staff-blocklist ---------------------------------------------------
  'staffBlocklist.title': { ro: 'Blocklist beneficiari', en: 'Recipient blocklist' },
  'staffBlocklist.subtitle': {
    ro: 'IBAN-uri refuzate direct la transfer, înainte de orice scoring — vezi BEN-04.',
    en: 'IBANs rejected directly at transfer time, before any scoring — see BEN-04.',
  },
  'staffBlocklist.addIban': { ro: 'Adaugă IBAN', en: 'Add IBAN' },
  'staffBlocklist.loadErrorTitle': { ro: 'Nu am putut încărca lista', en: 'We could not load the list' },
  'staffBlocklist.loadError': { ro: 'Nu am putut încărca lista de blocare.', en: 'We could not load the blocklist.' },
  'staffBlocklist.emptyTitle': { ro: 'Niciun beneficiar blocat', en: 'No blocked recipients' },
  'staffBlocklist.emptyDescription': {
    ro: 'Adaugă un IBAN pentru a-l refuza direct la orice transfer, indiferent de scor.',
    en: 'Add an IBAN to reject it directly on any transfer, regardless of score.',
  },
  'staffBlocklist.remove': { ro: 'Elimină', en: 'Remove' },
  'staffBlocklist.sourceAuto': { ro: 'Automat — fraudă confirmată', en: 'Automatic — confirmed fraud' },
  'staffBlocklist.sourceManual': { ro: 'Manual', en: 'Manual' },
  'staffBlocklist.addModalTitle': { ro: 'Adaugă beneficiar pe blocklist', en: 'Add recipient to blocklist' },
  'staffBlocklist.ibanLabel': { ro: 'IBAN', en: 'IBAN' },
  'staffBlocklist.reasonLabel': { ro: 'Motiv (opțional)', en: 'Reason (optional)' },
  'staffBlocklist.reasonPlaceholder': {
    ro: 'Ex: semnalat de intel extern, cont mulă cunoscut...',
    en: 'e.g. flagged by external intel, known mule account...',
  },
  'staffBlocklist.addToList': { ro: 'Adaugă pe listă', en: 'Add to list' },
  'staffBlocklist.ibanRequired': { ro: 'IBAN-ul este obligatoriu.', en: 'IBAN is required.' },
  'staffBlocklist.addError': { ro: 'Nu am putut adăuga IBAN-ul pe listă.', en: 'We could not add the IBAN to the list.' },
  'staffBlocklist.addedToast': {
    ro: '{iban} a fost adăugat pe lista de blocare.',
    en: '{iban} has been added to the blocklist.',
  },
  'staffBlocklist.removedToast': {
    ro: '{iban} a fost scos de pe lista de blocare.',
    en: '{iban} has been removed from the blocklist.',
  },
  'staffBlocklist.removeError': { ro: 'Nu am putut elimina intrarea.', en: 'We could not remove the entry.' },
  'staffBlocklist.removeConfirmTitle': { ro: 'Elimini beneficiarul de pe listă?', en: 'Remove the recipient from the list?' },
  'staffBlocklist.removeConfirmMessage': {
    ro: 'Transferurile către {iban} vor fi din nou permise (supuse scoring-ului normal, ca orice alt beneficiar).',
    en: 'Transfers to {iban} will be allowed again (subject to normal scoring, like any other recipient).',
  },

  // --- staff-documents -----------------------------------------------------
  'staffDocuments.title': { ro: 'Documente de semnat', en: 'Documents to sign' },
  'staffDocuments.subtitle': {
    ro: 'Trimite documente (PDF) clienților pentru semnare virtuală — vezi statusul mai jos.',
    en: 'Send documents (PDF) to customers for virtual signing — see status below.',
  },
  'staffDocuments.sendDocument': { ro: 'Trimite document', en: 'Send document' },
  'staffDocuments.loadErrorTitle': { ro: 'Nu am putut încărca documentele', en: 'We could not load the documents' },
  'staffDocuments.loadError': {
    ro: 'Nu am putut încărca documentele trimise.',
    en: 'We could not load the sent documents.',
  },
  'staffDocuments.emptyTitle': { ro: 'Niciun document trimis', en: 'No documents sent' },
  'staffDocuments.emptyDescription': {
    ro: 'Trimite primul document unui client pentru semnare virtuală.',
    en: 'Send the first document to a customer for virtual signing.',
  },
  'staffDocuments.statusSigned': { ro: 'Semnat', en: 'Signed' },
  'staffDocuments.statusCancelled': { ro: 'Anulat', en: 'Cancelled' },
  'staffDocuments.statusPending': { ro: 'În așteptare', en: 'Pending' },
  'staffDocuments.customerLabel': { ro: 'Client', en: 'Customer' },
  'staffDocuments.customerPlaceholder': { ro: 'Nume sau email...', en: 'Name or email...' },
  'staffDocuments.titleLabel': { ro: 'Titlu document', en: 'Document title' },
  'staffDocuments.titlePlaceholder': { ro: 'Ex: Contract de credit', en: 'e.g. Loan agreement' },
  'staffDocuments.fileLabel': { ro: 'Fișier PDF (max 5MB)', en: 'PDF file (max 5MB)' },
  'staffDocuments.send': { ro: 'Trimite', en: 'Send' },
  'staffDocuments.chooseCustomer': {
    ro: 'Alege un client din rezultatele căutării.',
    en: 'Choose a customer from the search results.',
  },
  'staffDocuments.titleRequired': { ro: 'Titlul este obligatoriu.', en: 'The title is required.' },
  'staffDocuments.choosePdf': { ro: 'Alege un fișier PDF.', en: 'Choose a PDF file.' },
  'staffDocuments.fileTooLarge': { ro: 'Fișierul este prea mare (limită 5MB).', en: 'The file is too large (5MB limit).' },
  'staffDocuments.fileReadError': {
    ro: 'Nu am putut citi fișierul — încearcă din nou.',
    en: 'We could not read the file — try again.',
  },
  'staffDocuments.sendError': { ro: 'Nu am putut trimite documentul.', en: 'We could not send the document.' },
  'staffDocuments.sentToast': {
    ro: 'Documentul a fost trimis către {name}.',
    en: 'The document has been sent to {name}.',
  },
  'staffDocuments.cancelConfirmTitle': { ro: 'Anulezi documentul?', en: 'Cancel the document?' },
  'staffDocuments.cancelConfirmMessage': {
    ro: "Clientul ({name}) nu va mai putea semna '{title}'.",
    en: "The customer ({name}) will no longer be able to sign '{title}'.",
  },
  'staffDocuments.cancelDocumentButton': { ro: 'Anulează documentul', en: 'Cancel document' },
  'staffDocuments.cancelledToast': { ro: 'Documentul a fost anulat.', en: 'The document has been cancelled.' },
  'staffDocuments.cancelError': { ro: 'Nu am putut anula documentul.', en: 'We could not cancel the document.' },

  // --- staff-customer ---------------------------------------------------
  'staffCustomer.title': { ro: 'Contul clientului', en: 'Customer account' },
  'staffCustomer.subtitle': {
    ro: 'Vedere read-only, deschisă din revizuirea unei rețineri de fraudă.',
    en: 'Read-only view, opened from reviewing a fraud hold.',
  },
  'staffCustomer.backToHolds': { ro: 'Înapoi la rețineri', en: 'Back to holds' },
  'staffCustomer.loadErrorTitle': {
    ro: 'Nu am putut încărca datele clientului',
    en: 'We could not load the customer data',
  },
  'staffCustomer.loadError': {
    ro: 'Nu am putut încărca datele clientului.',
    en: 'We could not load the customer data.',
  },
  'staffCustomer.missingUserId': { ro: 'Lipsește identificatorul clientului.', en: 'Missing customer identifier.' },
  'staffCustomer.accounts': { ro: 'Conturi', en: 'Accounts' },
  'staffCustomer.noAccountsTitle': { ro: 'Niciun cont', en: 'No accounts' },
  'staffCustomer.noAccountsDescription': {
    ro: 'Acest client nu are conturi active.',
    en: 'This customer has no active accounts.',
  },
  'staffCustomer.recentTransactions': { ro: 'Tranzacții recente', en: 'Recent transactions' },
  'staffCustomer.noTransactionsTitle': { ro: 'Nicio tranzacție', en: 'No transactions' },
  'staffCustomer.noTransactionsDescription': {
    ro: 'Nu există tranzacții înregistrate pentru acest client.',
    en: 'There are no transactions recorded for this customer.',
  },

  // --- staff-loan-applications --------------------------------------------
  'staffLoanApplications.title': { ro: 'Cereri de credit', en: 'Loan applications' },
  'staffLoanApplications.subtitle': {
    ro: 'Cereri în așteptare, în ordinea depunerii — verifică venitul real înainte de a decide.',
    en: 'Applications awaiting review, in submission order — check the real income before deciding.',
  },
  'staffLoanApplications.loadErrorTitle': { ro: 'Nu am putut încărca cererile', en: 'We could not load the applications' },
  'staffLoanApplications.loadError': { ro: 'Nu am putut încărca cererile de credit.', en: 'We could not load the loan applications.' },
  'staffLoanApplications.emptyTitle': { ro: 'Nicio cerere în așteptare', en: 'No applications pending' },
  'staffLoanApplications.emptyDescription': {
    ro: 'Toate cererile de credit au fost deja analizate.',
    en: 'All loan applications have already been reviewed.',
  },
  'staffLoanApplications.unknownApplicant': { ro: 'Client necunoscut', en: 'Unknown customer' },
  'staffLoanApplications.recommended': { ro: 'Eligibilitate: recomandat', en: 'Eligibility: recommended' },
  'staffLoanApplications.notRecommended': { ro: 'Eligibilitate: sub prag', en: 'Eligibility: below threshold' },
  'staffLoanApplications.realIncome': { ro: 'Venit real mediu:', en: 'Real average income:' },
  'staffLoanApplications.maxAffordable': { ro: 'Rată maximă suportabilă', en: 'Max affordable instalment' },
  'staffLoanApplications.existingInstalments': { ro: 'Rate active deja', en: 'Existing active instalments' },
  'staffLoanApplications.declaredIncome': { ro: 'Venit declarat de client', en: 'Customer-declared income' },
  'staffLoanApplications.viewDetails': { ro: 'Vezi detalii', en: 'View details' },
  'staffLoanApplications.detailsTitle': { ro: 'Detalii cerere de credit', en: 'Loan application details' },
  'staffLoanApplications.eligibilityTitle': { ro: 'Eligibilitate (automat, din istoric)', en: 'Eligibility (automatic, from history)' },
  'staffLoanApplications.questionnaireTitle': { ro: 'Chestionarul clientului', en: "Customer's questionnaire" },
  'staffLoanApplications.approve': { ro: 'Aprobă', en: 'Approve' },
  'staffLoanApplications.reject': { ro: 'Respinge', en: 'Reject' },
  'staffLoanApplications.approveToast': {
    ro: 'Credit aprobat — suma a fost creditată în contul clientului.',
    en: "Loan approved — the amount has been credited to the customer's account.",
  },
  'staffLoanApplications.approveError': { ro: 'Nu am putut aproba cererea.', en: 'We could not approve the application.' },
  'staffLoanApplications.rejectModalTitle': { ro: 'Respingi cererea de credit?', en: 'Reject the loan application?' },
  'staffLoanApplications.rejectHint': {
    ro: 'Explică pe scurt de ce respingi cererea lui {name} — motivul îi va fi trimis ca notificare.',
    en: "Briefly explain why you're rejecting {name}'s application — the reason will be sent to them as a notification.",
  },
  'staffLoanApplications.reasonLabel': { ro: 'Motiv', en: 'Reason' },
  'staffLoanApplications.reasonPlaceholder': {
    ro: 'Ex: venitul real din istoric nu acoperă rata solicitată...',
    en: "e.g. real income from history doesn't cover the requested instalment...",
  },
  'staffLoanApplications.reasonRequired': { ro: 'Motivul trebuie să aibă cel puțin 3 caractere.', en: 'The reason must be at least 3 characters.' },
  'staffLoanApplications.rejectToast': { ro: 'Cerere respinsă.', en: 'Application rejected.' },
  'staffLoanApplications.rejectError': { ro: 'Nu am putut respinge cererea.', en: 'We could not reject the application.' },
};
